# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-01 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AddField(
            model_name='delicounter',
            name='cheese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheese', to='products.Product'),
        ),
        migrations.AddField(
            model_name='delicounter',
            name='cured_meats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cured_meats', to='products.Product'),
        ),
        migrations.AddField(
            model_name='delicounter',
            name='fresh_meat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fresh_meat', to='products.Product'),
        ),
        migrations.AddField(
            model_name='delicounter',
            name='fruit_veg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fruit_veg', to='products.Product'),
        ),
    ]
