# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-23 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200122_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=150)),
                ('publisher', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('pub_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.Catalog')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.CatalogCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductAttribute')),
            ],
        ),
        migrations.RemoveField(
            model_name='delicounter',
            name='cheese',
        ),
        migrations.RemoveField(
            model_name='delicounter',
            name='cured_meats',
        ),
        migrations.RemoveField(
            model_name='delicounter',
            name='fresh_meat',
        ),
        migrations.RemoveField(
            model_name='delicounter',
            name='fruit_veg',
        ),
        migrations.RemoveField(
            model_name='delicounter',
            name='product',
        ),
        migrations.RemoveField(
            model_name='drystore',
            name='flour',
        ),
        migrations.RemoveField(
            model_name='drystore',
            name='herbs',
        ),
        migrations.RemoveField(
            model_name='drystore',
            name='oil',
        ),
        migrations.RemoveField(
            model_name='drystore',
            name='pasta',
        ),
        migrations.RemoveField(
            model_name='frozen',
            name='fish',
        ),
        migrations.RemoveField(
            model_name='frozen',
            name='meats',
        ),
        migrations.RemoveField(
            model_name='frozen',
            name='product',
        ),
        migrations.RemoveField(
            model_name='frozen',
            name='ready_meals',
        ),
        migrations.RemoveField(
            model_name='frozen',
            name='vegetables',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='red',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='sparkling',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='spirits',
        ),
        migrations.RemoveField(
            model_name='wine',
            name='white',
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=254),
        ),
        migrations.DeleteModel(
            name='DeliCounter',
        ),
        migrations.DeleteModel(
            name='DryStore',
        ),
        migrations.DeleteModel(
            name='Frozen',
        ),
        migrations.DeleteModel(
            name='Wine',
        ),
        migrations.AddField(
            model_name='productdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='products.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.CatalogCategory'),
        ),
    ]
