# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-23 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200123_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogcategory',
            name='catalog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.Catalog'),
        ),
        migrations.AlterField(
            model_name='catalogcategory',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.CatalogCategory'),
        ),
    ]
