# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-01 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200101_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='delicounter',
            name='name',
            field=models.CharField(default='', max_length=254),
        ),
    ]
