# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-01 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_delicounter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delicounter',
            name='name',
        ),
    ]
