# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-01 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_delicounter_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DryStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flour', to='products.Product')),
                ('herbs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='herbs', to='products.Product')),
                ('oil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oil', to='products.Product')),
                ('pasta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pasta', to='products.Product')),
            ],
        ),
    ]
