# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-01 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_frozen_wines'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wines',
            new_name='Wine',
        ),
    ]
